### ISSUE TITLE
Verify/Fix creation of the capped collection in the Edge Variant

### ISSUE THREAD

**Issue by aleskandro** [mora-resource-allocation-edge-cloud/mora#2] opened 2021-06-25 07:04 UTC
In the helm template, the creation of the capped collection must be achieved by a one-shot job at the deployment stage.

In particular, the job has to use Mongo credentials available in the secrets and configmaps already used by the VMS and the MongoDB deployments.

The job will create the capped collection using a 1-line shell script.

## Implementation hints

Use the [mongoclient/mongoclient](https://hub.docker.com/r/mongoclient/mongoclient/) image for the job and the following command:

```sh
mongo $MONGODB_HOST:$MONGODB_PORT/$MONGODB_DATABASE -u $MONGODB_USER -p $MONGODB_PASSWORD \
--eval="db.createCollection('video', {
   capped: true, 
  size: {{ .Values.mongo.videoCollectionSize }}, 
  max: {{ .Values.mongo.videoCollectionMaxDocs }} 
})"
```

where: 

`{{ .Values.mongo.videoCollectionSize }}` and `{{ .Values.mongo.videoCollectionMaxDocs }}` are replaced by the (provided) helm values file.

Finally, this job has to be deployed only if the helm boolean `isCloud` is set to `false`.

**Comment by zazim13** [comment] 2021-07-01 15:28
Hi @aleskandro . The video collection was not created automatically in the edge because the edge was not able to download any video from the cloud. In fact the java application (In the edge) was not able to resolve cloud-vms-1.master.particles.dieei.unict.i to an ip address. I solved the problem by adding the configuration HostAliases in the vms config file. (It will add entries to pod /etc/hosts ). 
I just pushed changes in minikubebranch. 
[see this link to the specific line](https://github.com/mora-resource-allocation-edge-cloud/deployment/blob/fa93ab2076c9b9a9c49617ca368db832fc70cc85/vp-cloud/templates/02-videomanagement.yml#L24)

Now,  when a video is only available in the cloud and that I ask the edge this video, a video collection is created in the edge if not already created before. This operation is done in the code somewhere (I have to find which part of the code does that).

The problem that the collection created as above is not capped.

I have also implemented the mongoclient. It can connect to mongodb and send requests (through a web interface). Next step will be to automate the creation of the capped collection at deployment. Or turn an existing video collection to a capped collection.
I will keep you updated.

**Comment by aleskandro** [comment] 2021-07-02 07:31
Hi @zazim13, we cannot use static ips in that line. Please, remove it.

Actually, from a network perspective:

- `cloud-vms-1.master.particles.dieei.unict.it` has to be changed into cloudmora.eu which is registered, has globally available nameservers related to it and a well-defined dns zone that get us able to reach videos in the "cloud variant". So, we can just modify the default `values.yaml` file replacing that url with the new one: `s/cloud-vms-1.master.particles.dieei.unict.it/cloudmora.eu/`. I do not know which service are you reaching by 172.16.0.43. But probably, when we'll deploy somewhere else the software it will not be able to reach this private address. Finally, if that address is currently related to the nginx k8s service of the cloud variant, whenever we'll delete the service and re-apply it, it is not guaranteed that this ip will be still the right one. hostnames are used, overall, for this reason.
- Any "edge variant" (offline, cache, online...) will be able to download videos from the cloud version
- Yes, the created collection is not capped: moreover, to my knowledge we cannot convert a "standard" collection into a "capped" collection after its creation.

So I would suggest again to add a job in the helm template to be deployed only if isCloud is set to false. This job will create the collection with the command in the description of the issue. Any other problem, like the "hostname reachabilty" of the cloud variant, maybe, would be better described in the readme.

**Comment by aleskandro** [comment] 2021-07-02 07:46
a new file, like the following one (to be fixed/verified, maybe the command definition could be bugged) should work:

```yaml
{{ if eq .Values.isCloud true }}
apiVersion: batch/v1
kind: Job
metadata:
  name: create-collection-{{ now | date "20060102150405" }}
spec:
  completions: 1
  backoffLimit: 3
  parallelism: 1
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      labels:
        job: create-collection
    spec:
      restartPolicy: OnFailure
      containers:
        - name: collection-create
          image: mongoclient/mongoclient 
          command:
            - sh
            - -c
            - "mongo  {{ .Values.mongodb.serviceName }}:27017/$MONGODB_DATABASE -u $MONGODB_USERNAME -p $MONGODB_PASSWORD --eval=\"db.createCollection('video', {capped: true,   size: {{ .Values.mongo.videoCollectionSize }},   max: {{ .Values.mongo.videoCollectionMaxDocs }} })\""
           - env:
             - name: MONGODB_USERNAME
               value: {{ .Values.mongodb.username }}
             - name: MONGODB_PASSWORD
               value: {{ .Values.mongodb.password }}
             - name: MONGODB_ADMIN_PASSWORD
               value: {{ .Values.mongodb.password }}
             - name: MONGODB_DATABASE
               value: {{ .Values.mongodb.databaseName }}
{{- end }}
```

- the name also has a timestamp as a workaround since jobs in kubernetes are immutable and an upgrade command could fail (better solutions are welcome).
- the command could not work correctly just because of the array definition.
- there is a MONGODB_ADMIN_PASSWORD defined in the mongodb deployment. Not sure whether if we have to use MONGODB_PASSWORD or MONGODB_ADMIN_PASSWORD. Just check what the VMS does.
- Completion is set to 1 since we need just one completion for the job
- backoffLimit is set to 3 just as to retry the job 3 times before considering it failed.
- ttlSecondsAfterFinished just remove the job from the kubernetes history after 1-hout it finished
- maybe, in this case, we do not need neither the deletion of the job nor that workaround to differentiate him between "helm upgrades": if we make once the creation of the collection, it will not be needed during upgrades of the same env. So, maybe we can remove the ttlSecondsAfterFinished and the second part of the job name. Just need to be verified.

**Comment by zazim13** [comment] 2021-07-06 18:25
(After the 8th of July meeting, I understood that there are a cloud server at Catania accessible at `cloudmora.eu`. But here I am deploying the edge and cloud clusters in different virtual machine in the same network.)
  
Hi @aleskandro. To be more precise about the problem of "reachability". [This ip address  ](https://github.com/mora-resource-allocation-edge-cloud/deployment/blob/fa93ab2076c9b9a9c49617ca368db832fc70cc85/vp-cloud/templates/02-videomanagement.yml#L25) is the ip address of the cloud VM. The problem is that when a video is available in the cloud but not in the edge and I ask the edge this video, the vms has to send a request to `http://cloud-vms-1.master.particles.dieei.unict.it`. But the host name `cloud-vms-1.master.particles.dieei.unict.it` is unknown. With this entry, the hostname is associated with the ip address of the VM hosting the cloud cluster, and then video is successfully downloaded by the edge. 
My idea was to mention in the readme that this ip has to be changed into the ip of the VM hosting the cloud cluster. 

However your solution seems to be more global. But I am not sure that I understand what you mean. You suggest to replace the value of the variable cloudURL `cloud-vms-1.master.particles.dieei.unict.it` by this new value `cloudmora.eu` ?

**Comment by aleskandro** [comment] 2021-07-12 07:31
Hi @zazim13, as anticipated in the meeting, I was suggesting to replace the URL (cloud-vms.1.master.particles.dieei.unict.it) with the public available one: cloudmora[dot]eu.

The original one is the domain name that can be resolved only within the University of Catania cluster through an internal DNS server.
Instead, cloudmora.eu, is registered through public DNS Nameservers. I can also provide  (in pvt) credentials to add other rules in the zone (e.g., for the dash player or the metrics collector).

As we're going to use the cloud variant deployed at University of Catania's cluster, just using it would be enough.

As for documentation purposes, we shall suggest to use a DNS server in order to make both the clients and the internal containers (essentially the edge variants have to know how to resolve the domain name of the cloud variant). This is the recommended way.

## Configuration with no dns server

### Clients

Set properly the clients' hosts file (i.e., /etc/hosts for *nix operative systems)  with a line like the following:
```
$IP_ADDRESS $CLOUD_VMS_DOMAIN_NAME
```
where
- $IP_ADDRESS is the ip of the machine executing the ingress container and
- $CLOUD_VMS_DOMAIN_NAME is the domain name of the cloud variant as specified in the `values.yaml` file of the Helm template

This will make the cloud domain name available for the clients.

### Let the (edge) containers resolve the Cloud variant services

To let the Edge variants' containers able to both download videos from the Cloud variant  and balance the traffic between the Edge containers and the cloud containers, with no DNS server available, a user should provide the IP address to fulfill the hostAliases as you did.

If we want to allow users also this second way we should do something like:

1. add a `noDNSServerForCloud` field in the `values.yaml` file. The value of this field has to be `false` by default.
2. add a `CloudIP` to the `routes` map in the `values.yaml` file. The default value has to be the empty string
3. In the deployments that need this mapping, the load balancer and the vms, we have to add the hostAliases as you did, but only if `noDNSServerForCloud` is set to `true`:

For instance, at rows around https://github.com/mora-resource-allocation-edge-cloud/deployment/blob/fa93ab2076c9b9a9c49617ca368db832fc70cc85/vp-cloud/templates/02-videomanagement.yml#L25,
we should add something like:

```yaml
{{- if eq .Values.noDNSServerForCloud true }}
hostAliases:
[......]
{{- end }}
```

Do we really want to pursue this way? (@andreaaraldo).
I don't think it's a high-priority and I think it's not so helpful. 

Usually, people deploying this kind of software are able to configure the first solution. I have never seen software of this kind not being related/coupled to hostnames in the way we already have out of the box (no IPs). 

I usually see the requirement of setting properly the hostnames where needed.

**Comment by aleskandro** [comment] 2021-07-12 07:32
I'm going to move my last comment to another issue. The topic of this one is not about domain names, dns and so on...

**Comment by zazim13** [comment] 2021-07-15 14:10
In the case of multiple mongodb replicas. The Job is creating a capped video collection only in one pod. 
1. Other mongodb pods don't have this video collection.
2. If new replicas of mongodb are added they don't have this collection either.

**Comment by aleskandro** [comment] 2021-07-15 14:28
No multiple replicas of mongodb were considered till now. In order to allow them we have to look at scalability issues of mongodb.

>> Scaling MongoDB horizontally is achieved through sharding (preferred) and replica sets.

Sharding is not so needed for an edge service that uses a capped collection for low sizes. Finally, we should also convert the current Deployment of MongoDB into a statefulset in order to better handle, maybe, issues like master elections, consensus on shards and similar (need to investigate how MongoDB actually handle sharding or replica sets).

However, what I'd suggest is to mantain 1 only replica for MongoDB and scaling, as usual, the stateless VMS which is a lot easier (just increasing the number of replicas of its deployment).

# References

https://www.mongodb.com/basics/scaling

**Comment by zazim13** [comment] 2021-07-23 09:22
Hi @aleskandro 
So you suggest to just close this issue or to also open a new one about sharding (My question is will it be needed in our case)?

**Comment by aleskandro** [comment] 2021-07-23 09:45
No, it is not needed currently

**Closed as completed** 2021-07-23 09:59 UTC
Labels: bug, enhancement
